# Generated by Django 4.2.6 on 2024-11-17 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='Detailed explanation about the topic.')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules_list', to='mainapp.course')),
            ],
        ),
    ]
