# Generated by Django 4.2.6 on 2024-11-17 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_forum_post_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='forum',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='topic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Forum',
        ),
    ]
