# Generated by Django 4.2.6 on 2024-12-08 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='constraints',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='problem',
            name='input_format',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='problem',
            name='output_format',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='problem',
            name='test_cases',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='problem',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
