# Generated by Django 4.2.6 on 2024-12-08 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_submission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='constraints',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='input_format',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='output_format',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='test_cases',
        ),
        migrations.AlterField(
            model_name='problem',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
