# Generated by Django 4.2.6 on 2025-04-23 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_remove_problem_constraints_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='https://pngtree.com/free-png-vectors/default-avatar', upload_to='avatars/'),
        ),
    ]
